### ISSUE TITLE
SMB World 1-1 Segmentation Map and Key.

### ISSUE THREAD

**Issue by MiLO83** [cloneofsimo/paint-with-words-sd#19]
![SegmentationMap](https://user-images.githubusercontent.com/5951434/207748113-ce187653-a03a-4a1f-97b0-f1edf6ebdcc1.png)

[https://drive.google.com/file/d/17kXJErBBRQSe8GyqUhbxeho0jCsepuMI/view?usp=share_link](url)

(0,0,0): "Black,1.0",
(1,1,1): "Cave,1.0",
(2,2,2): "Cave,1.0",
(3,3,3): "Cave,1.0",
(4,4,4): "Cave,1.0",
(5,5,5): "Green Sewer Pipe,1.0",
(6,6,6): "Green Sewer Pipe,1.0",
(7,7,7): "Green Sewer Pipe,1.0",
(8,8,8): "Green Sewer Pipe,1.0",
(9,9,9): "Green Sewer Pipe,1.0",
(10,10,10): "Green Sewer Pipe,1.0",
(11,11,11): "Green Sewer Pipe,1.0",
(12,12,12): "Green Sewer Pipe,1.0",
(13,13,13): "Green Sewer Pipe,1.0",
(14,14,14): "Green Sewer Pipe,1.0",
(15,15,15): "Green Sewer Pipe,1.0",
(16,16,16): "Green Sewer Pipe,1.0",
(17,17,17): "Green Sewer Pipe,1.0",
(18,18,18): "Green Sewer Pipe,1.0",
(19,19,19): "Green Sewer Pipe,1.0",
(20,20,20): "Green Sewer Pipe,1.0",
(21,21,21): "Green Sewer Pipe,1.0",
(22,22,22): "Red Soil,1.0",
(23,23,23): "Red Soil,1.0",
(24,24,24): "Red Soil,1.0",
(25,25,25): "Sky,1.0",
(26,26,26): "Red Soil,1.0",
(27,27,27): "Red Soil,1.0",
(28,28,28): "Grassy Hill,1.0",
(29,29,29): "Grassy Hill,1.0",
(30,30,30): "Green Bush,1.0",
(31,31,31): "Green,1.0",
(32,32,32): "Green Bush,1.0",
(33,33,33): "Green Sewer Pipe,1.0",
(34,34,34): "Green Sewer Pipe,1.0",
(35,35,35): "Orange Block,1.0",
(36,36,36): "Orange Block,1.0",
(37,37,37): "Orange Bricks,1.0",
(38,38,38): "Green Bush,1.0",
(39,39,39): "Green Bush,1.0",
(40,40,40): "Orange Block,1.0",
(41,41,41): "Orange Block,1.0",
(42,42,42): "Grassy Hill,1.0",
(43,43,43): "Grassy Hill,1.0",
(44,44,44): "Green Sewer Pipe,1.0",
(45,45,45): "Green Sewer Pipe,1.0",
(46,46,46): "Green Sewer Pipe,1.0",
(47,47,47): "Sky,1.0",
(48,48,48): "Sky,1.0",
(49,49,49): "Green Sewer Pipe,1.0",
(50,50,50): "Green Sewer Pipe,1.0",
(51,51,51): "Green Sewer Pipe,1.0",
(52,52,52): "Green Sewer Pipe,1.0",
(53,53,53): "Castle Door,1.0",
(54,54,54): "Castle Door,1.0",
(55,55,55): "Castle,1.0",
(56,56,56): "Castle,1.0",
(57,57,57): "Castle,1.0",
(58,58,58): "Castle,1.0",
(59,59,59): "Mario Bros Question Mark Block,1.0",
(60,60,60): "Mario Bros Question Mark Block,1.0",
(61,61,61): "Mario Bros Question Mark Block,1.0",
(62,62,62): "Mario Bros Question Mark Block,1.0",
(63,63,63): "Orange Bricks,1.0",
(64,64,64): "Fluffy Cloud,1.0",
(65,65,65): "Fluffy Cloud,1.0",
(66,66,66): "Fluffy Cloud,1.0",
(67,67,67): "Fluffy Cloud,1.0",
(68,68,68): "Fluffy Cloud,1.0",
(69,69,69): "Fluffy Cloud,1.0",
(70,70,70): "Fluffy Cloud,1.0",
(71,71,71): "Fluffy Cloud,1.0",
(72,72,72): "Fluffy Cloud,1.0",
(73,73,73): "Grassy Cliff Edge,1.0",
(74,74,74): "Grassy Cliff Edge,1.0",

`CompVis/stable-diffusion-v1-4
Warning ratio 8 : tokens [1449] not found in text
Warning ratio 16 : tokens [1449] not found in text
Warning ratio 32 : tokens [1449] not found in text
Warning ratio 64 : tokens [1449] not found in text
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\paint-with-words-sd\smb.py", line 23, in <module>
    img = paint_with_words(
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\paint-with-words-sd\paint_with_words\paint_with_words.py", line 360, in paint_with_words
    noise_pred_uncond = unet(
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\diffusers\models\unet_2d_condition.py", line 341, in forward
    sample, res_samples = downsample_block(
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 644, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\diffusers\models\attention.py", line 219, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\rxcam\miniconda3\envs\sd-inf\lib\site-packages\diffusers\models\attention.py", line 483, in forward
    hidden_states = self.attn2(norm_hidden_states, context=context) + hidden_states
  File "C:\paint-with-words-sd\paint_with_words\paint_with_words.py", line 77, in inj_forward
    w = context[f"CROSS_ATTENTION_WEIGHT_{attention_size_of_img}"]
KeyError: 'CROSS_ATTENTION_WEIGHT_3584'`

I have written a TOOL which dissects PNG 2D videogame maps (NES, SNES, GBA, SEGA ETC) into Segmentation maps / keys for use with this REPO. When I run the output I get the above error. When I run runner.py I get a kitten and the dog is missing :/

I have also heavily modified an NES Emulator and am working on loading these outputs right back INTO the games so the new graphics replace the old ones in-game.

I have all the maps for SMB1 output like this.
Interested to see if you can get some outputs, as I just get the above error and I don't know how to fix it.
  - MiLO

**Comment by mittski** [comment]
> When I run runner.py I get a kitten and the dog is missing :/
you have to change filenames in runner.py from example, plug in the right example to the function at the bottom of that file
its still trying to run off the example images packaged with the repo
