### ISSUE TITLE
Only exception after runner.py

### ISSUE THREAD

**Issue by DoctorMG** [cloneofsimo/paint-with-words-sd#8]
OS: Win10, no CUDA
token (type: read) was set, runner.py was startet and only a casade of exceptions is given:

Traceback (most recent call last):
  File "E:\Programme\Anaconda3\envs\apps\lib\site-packages\huggingface_hub\utils\_errors.py", line 213, in hf_raise_for_status
    response.raise_for_status()
  File "E:\Programme\Anaconda3\envs\apps\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/CompVis/stable-diffusion-v1-4/resolve/main/vae/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Programme\Anaconda3\envs\apps\lib\site-packages\diffusers\modeling_utils.py", line 394, in from_pretrained
    model_file = hf_hub_download(
  File "E:\Programme\Anaconda3\envs\apps\lib\site-packages\huggingface_hub\file_download.py", line 1053, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "E:\Programme\Anaconda3\envs\apps\lib\site-packages\huggingface_hub\file_download.py", line 1359, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "E:\Programme\Anaconda3\envs\apps\lib\site-packages\huggingface_hub\utils\_errors.py", line 254, in hf_raise_for_status
    raise HfHubHTTPError(str(HTTPError), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: <class 'requests.exceptions.HTTPError'> (Request ID: iJKkSfoiLnBa4bMVHLKZ2)

**Comment by shreydan** [comment]
the error is 403 Client Error: Forbidden for url. To fix this go to [CompVis/stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4) and accept the model license agreement and then it'll work

**Comment by cloneofsimo** [comment]
@DoctorMG did this work? Ill close this issue if so.
